/* 
List of movements should have few attributes:
- key: Title of the movement
- link: to get more details about the movement
- description: which will described the movement
*/
export const MOVEMENT_LIST = [
    { key: 'Back Squat', description: 'The back squat requires the structures of the lower body and core to work synergistically. Optimal performance requires an adequate range of motion at the ankles, hips, and knees; superior lower-body strength; and a tremendous amount of core stability.', link: 'https://www.crossfit.com/essentials/the-back-squat' },
    { key: 'Clean', link: 'https://www.crossfit.com/essentials/the-clean-2', description: 'The clean is a pure bit of functionality. The clean is simply pulling a load from the ground to the shoulders, where frequently the object is being readied for lifting overhead. With the clean, we take ourselves from standing over an object and pulling it to moving under it and supporting it.' },
    { key: 'Clean & Jerk', link: 'https://www.crossfit.com/essentials/the-clean-and-jerk', description: 'In the most common variation of the clean and jerk, the athlete receives the load in a full front squat, then uses the split position in the jerk. For most athletes, these positions allow for the greatest loads to be lifted. During the clean, the athlete must pull the weight only as high as needed to move into the bottom of the squat. During the split jerk, the torso can remain vertical while demanding less shoulder and thoracic flexibility than a squat or power jerk.' },
    { key: 'Deadlift', description: 'The deadlift, being no more than the safe and sound approach by which any object should be lifted from the ground, keeps company with standing, running, jumping, and throwing for functionality but imparts quick and prominent athletic advantage like no other exercise. It is unrivaled in its simplicity and impact while unique in its capacity for increasing head-to-toe strength.', link: 'https://www.crossfit.com/essentials/the-deadlift' },
    { key: 'Front squat', description: 'The front squat builds exactly on the mechanics of the air squat. All that is added is a load supported in the front-rack position, where the weight sits squarely on the upper chest and shoulders, and the elbows point forward to bring the upper arms parallel to the floor. This “rack position,” critical to weightlifting, both demands and improves wrist and shoulder flexibility while the load, supported by the torso, both demands and improves midline stability.', link: 'https://www.crossfit.com/essentials/the-front-squat' },
    { key: 'Overhead Squat', description: 'The overhead squat is the ultimate core exercise and peerless in developing effective athletic movement. This functional gem trains for efficient transfer of energy from large to small body parts and improves functional flexibility. Similarly, it develops the squat by amplifying and cruelly punishing faults in posture, movement, and stability. The overhead squat is to midline control, stability and balance what the clean and snatch are to power—unsurpassed.', link: 'https://www.crossfit.com/essentials/the-overhead-squat' },
    { key: 'Push Press', description: 'In the push press, the core-to-extremity principle is obvious as the muscles of the power zone — including the hip flexors, hip extensors (glutes and hams), spinal erectors, and quadriceps — assist the arms in driving the barbell overhead. With the push press, you will be able to move overhead as much as 30% more weight than with the shoulder press. Regular practice of the push press — and the push jerk — develops power and speed, which are critical to effective and efficient athletic movement. —Adapted from “The Overhead Lifts” by Greg Glassman', link: 'https://www.crossfit.com/essentials/the-push-press' },
    { key: 'Snatch', description: 'The Olympic lifts train athletes to effectively activate more muscle fibers more rapidly than through any other modality of training. The explosiveness that results from this training is of vital necessity to every sport. Practicing the snatch teaches one to apply force to muscle groups in proper sequence — i.e., from the center of the body to its extremities (core to extremity). Learning this vital technical lesson benefits all athletes who need to impart force to another person or object, as is commonly required in nearly all sports.', link: 'https://www.crossfit.com/essentials/the-snatch' },
]